### ISSUE TITLE
Arduino Nano 33 IoT does a HCF when I run simple_test.ino from TMP117-Arduino library

### ISSUE THREAD

**Issue by tonyryan234** [NilsMinor/TMP117-Arduino#5]
Dear Nils Minor,

I have a simple issue with a Nano 33 IoT board.   I hope you can help me.

I have my computer connected to the Nano 33 IoT board with a USB cable.  There are no other connections to the Nano 33 IoT board.

When I load the simple_test.ino file from the TMP117-Arduino library, the board disconnects.   The software loads and then does not communicate with the Arduino application.

I have attached a file with the Arduino outputs.  Also I have cut and pasted the output below, in case the attachment does not work.

Thank you for your help.

Tony Ryan

[Nano33IoT_TMP117_issue .txt](https://github.com/NilsMinor/TMP117-Arduino/files/8026127/Nano33IoT_TMP117_issue.txt)

Sketch uses 21756 bytes (8%) of program storage space. Maximum is 262144 bytes.
Global variables use 4296 bytes (13%) of dynamic memory, leaving 28472 bytes for local variables. Maximum is 32768 bytes.
Forcing reset using 1200bps open/close on port COM7
PORTS {COM1, COM3, COM7, } / {COM1, COM3, COM7, } => {}
PORTS {COM1, COM3, COM7, } / {COM1, COM3, COM7, } => {}
PORTS {COM1, COM3, COM7, } / {COM1, COM3, COM7, } => {}
PORTS {COM1, COM3, COM7, } / {COM1, COM3, COM7, } => {}
PORTS {COM1, COM3, COM7, } / {COM1, COM3, COM7, } => {}
PORTS {COM1, COM3, COM7, } / {COM1, COM3, COM7, } => {}
PORTS {COM1, COM3, COM7, } / {COM1, COM3, COM7, } => {}
PORTS {COM1, COM3, COM7, } / {COM1, COM3, COM7, } => {}
PORTS {COM1, COM3, COM7, } / {COM1, COM3, COM7, } => {}
PORTS {COM1, COM3, COM7, } / {COM1, COM3, COM7, } => {}
PORTS {COM1, COM3, COM7, } / {COM1, COM3, COM7, } => {}
PORTS {COM1, COM3, COM7, } / {COM1, COM3, COM7, } => {}
PORTS {COM1, COM3, COM7, } / {COM1, COM3, COM7, } => {}
PORTS {COM1, COM3, COM7, } / {COM1, COM3, COM7, } => {}
PORTS {COM1, COM3, COM7, } / {COM1, COM3, COM7, } => {}
PORTS {COM1, COM3, COM7, } / {COM1, COM3, COM7, } => {}
PORTS {COM1, COM3, COM7, } / {COM1, COM3, COM7, } => {}
PORTS {COM1, COM3, COM7, } / {COM1, COM3, COM7, } => {}
PORTS {COM1, COM3, COM7, } / {COM1, COM3, COM7, } => {}
PORTS {COM1, COM3, COM7, } / {COM1, COM3, COM7, } => {}
Uploading using selected port: COM7
C:\Users\tony\AppData\Local\Arduino15\packages\arduino\tools\bossac\1.7.0-arduino3/bossac.exe -i -d --port=COM7 -U true -i -e -w -v C:\Users\tony\AppData\Local\Temp\arduino_build_448593/simple_test.ino.bin -R 
Set binary mode
readWord(addr=0)=0x20007ffc
readWord(addr=0xe000ed00)=0x410cc601
readWord(addr=0x41002018)=0x10010305
version()=v2.0 [Arduino:XYZ] Apr 19 2019 14:38:48
chipId=0x10010005
Connected at 921600 baud
readWord(addr=0)=0x20007ffc
readWord(addr=0xe000ed00)=0x410cc601
readWord(addr=0x41002018)=0x10010305
Atmel SMART device 0x10010005 found
write(addr=0x20004000,size=0x34)
writeWord(addr=0x20004030,value=0x10)
writeWord(addr=0x20004020,value=0x20008000)
Device       : ATSAMD21G18A
readWord(addr=0)=0x20007ffc
readWord(addr=0xe000ed00)=0x410cc601
readWord(addr=0x41002018)=0x10010305
Chip ID      : 10010005
version()=v2.0 [Arduino:XYZ] Apr 19 2019 14:38:48
Version      : v2.0 [Arduino:XYZ] Apr 19 2019 14:38:48
Address      : 8192
Pages        : 3968
Page Size    : 64 bytes
Total Size   : 248KB
Planes       : 1
Lock Regions : 16
Locked       : readWord(addr=0x41004020)=0xffff
readWord(addr=0x41004020)=0xffff
readWord(addr=0x41004020)=0xffff
readWord(addr=0x41004020)=0xffff
readWord(addr=0x41004020)=0xffff
readWord(addr=0x41004020)=0xffff
readWord(addr=0x41004020)=0xffff
readWord(addr=0x41004020)=0xffff
readWord(addr=0x41004020)=0xffff
readWord(addr=0x41004020)=0xffff
readWord(addr=0x41004020)=0xffff
readWord(addr=0x41004020)=0xffff
readWord(addr=0x41004020)=0xffff
readWord(addr=0x41004020)=0xffff
readWord(addr=0x41004020)=0xffff
readWord(addr=0x41004020)=0xffff
none
readWord(addr=0x41004018)=0
Security     : false
Boot Flash   : true
readWord(addr=0x40000834)=0x7000a
BOD          : true
readWord(addr=0x40000834)=0x7000a
BOR          : true
Arduino      : FAST_CHIP_ERASE
Arduino      : FAST_MULTI_PAGE_WRITE
Arduino      : CAN_CHECKSUM_MEMORY_BUFFER
Erase flash
chipErase(addr=0x2000)
done in 0.833 seconds

Write 21756 bytes to flash (340 pages)
write(addr=0x20005000,size=0x1000)
writeBuffer(scr_addr=0x20005000, dst_addr=0x2000, size=0x1000)
[=====                         ] 18% (64/340 pages)write(addr=0x20005000,size=0x1000)
writeBuffer(scr_addr=0x20005000, dst_addr=0x3000, size=0x1000)
[===========                   ] 37% (128/340 pages)write(addr=0x20005000,size=0x1000)
writeBuffer(scr_addr=0x20005000, dst_addr=0x4000, size=0x1000)
[================              ] 56% (192/340 pages)write(addr=0x20005000,size=0x1000)
writeBuffer(scr_addr=0x20005000, dst_addr=0x5000, size=0x1000)
[======================        ] 75% (256/340 pages)write(addr=0x20005000,size=0x1000)
writeBuffer(scr_addr=0x20005000, dst_addr=0x6000, size=0x1000)
[============================  ] 94% (320/340 pages)write(addr=0x20005000,size=0x500)
writeBuffer(scr_addr=0x20005000, dst_addr=0x7000, size=0x500)
[==============================] 100% (340/340 pages)
done in 0.175 seconds

Verify 21756 bytes of flash with checksum.
checksumBuffer(start_addr=0x2000, size=0x1000) = f0a8
checksumBuffer(start_addr=0x3000, size=0x1000) = 8a80
checksumBuffer(start_addr=0x4000, size=0x1000) = e518
checksumBuffer(start_addr=0x5000, size=0x1000) = 9a86
checksumBuffer(start_addr=0x6000, size=0x1000) = 88
checksumBuffer(start_addr=0x7000, size=0x4fc) = 42d0
Verify successful
done in 0.018 seconds
CPU reset.
readWord(addr=0)=0x20007ffc
readWord(addr=0xe000ed00)=0x410cc601
readWord(addr=0x41002018)=0x10010305
writeWord(addr=0xe000ed0c,value=0x5fa0004)
processing.app.SerialException: Error opening serial port 'COM7'.
	at processing.app.Serial.<init>(Serial.java:152)
	at processing.app.Serial.<init>(Serial.java:82)
	at processing.app.SerialPlotter$2.<init>(SerialPlotter.java:479)
	at processing.app.SerialPlotter.open(SerialPlotter.java:479)
	at processing.app.AbstractMonitor.resume(AbstractMonitor.java:132)
	at processing.app.Editor.resumeOrCloseSerialPlotter(Editor.java:2140)
	at processing.app.Editor.access$1400(Editor.java:117)
	at processing.app.Editor$UploadHandler.run(Editor.java:2090)
	at java.lang.Thread.run(Thread.java:748)
Caused by: jssc.SerialPortException: Port name - COM7; Method name - openPort(); Exception type - Port not found.
	at jssc.SerialPort.openPort(SerialPort.java:167)
	at processing.app.Serial.<init>(Serial.java:141)
	... 8 more
Error opening serial port 'COM7'.

**Comment by NilsMinor** [comment]
Hello Tony,

this is hard to tell what is going on. I think it is not directly related to the tmp117 library but I can imagine the following things, that creates the issue :

- Something with the baud rate is wrong. Note the example sketch opens a com-port with a baud rate of 115200. in your logs I found something with baud rate 1200 and 921600 ?
- Maybe the i2c-connection of the tmp117 sensor blocks the Arduino rx/tx lines that again blocks the serial communication via COM-port.

Let me know if this solves your issue :) Maybe you start with the sketch and uncomment the I2C related tmp117 commands and just try to print out some strings via COM-port.

- Nils

**Comment by tonyryan234** [comment]
Nils,

Thank you for getting back to me so quickly, and thank you for the suggestions.

I will take a closer look and let you know what I find.

All the best,

Tony

**Comment by tonyryan234** [comment]
Nils,

We are seeing this problem when there is no TMP117 hooked up to the Nano 33 IoT board.

That is, when we load the file simple_test.ino into the Nano 33 IoT board, with nothing else connected to it, then the Nano 33 IoT board is no longer visible to the Arduino workspace.

I have no idea what might be causing this.

Please let me know if you have any thoughts.

Thank you,

Tony



From: Tony Ryan
Sent: Tuesday, February 8, 2022 1:45 PM
To: NilsMinor/TMP117-Arduino ***@***.***>
Subject: RE: [NilsMinor/TMP117-Arduino] Arduino Nano 33 IoT does a HCF when I run simple_test.ino from TMP117-Arduino library (Issue #5)

Nils,

Thank you for getting back to me so quickly, and thank you for the suggestions.

I will take a closer look and let you know what I find.

All the best,

Tony

**Comment by NilsMinor** [comment]
Hey Tony,

this sounds odd to me. Have you checked the baud rate (115200) matches your set baud rate of you Arduino IDE?

Have you testet to remove the tmp lines like :https://github.com/NilsMinor/TMP117-Arduino/blob/b9352b7ac6e272610ca449d7d3716cff9a7fc857/examples/simple_test/simple_test.ino#L38 and https://github.com/NilsMinor/TMP117-Arduino/blob/b9352b7ac6e272610ca449d7d3716cff9a7fc857/examples/simple_test/simple_test.ino#L45
You could comment these lines in order to see if it really related to the library. Or start a new project with simple printouts via terminal to find the issue with your board.

Best regards,
Nils
